import random
print("Welcome to the Animal Accumulator.")
print("Animals cost and generate income according to their name length (e.g., a Zebra costs 5).")
print("Each day, animals generate income based on luck. Sometimes they escape.")
print("You can buy new animals with the income your animals generates.")

class AnimalAccumulator:
    def __init__(self):
        self.animals = ["Antelope", "Fox", "Zebra"]
        self.total_income = 0
        self.days_simulated = 0
        self.income_records = {}
        self.lucky_number = 0

    def welcome_message(self):
        print("Welcome to the Animal Accumulator.")

    def generate_lucky_number(self):
        self.lucky_number = random.randint(1, 100)

    def accumulate_income(self):
        for animal in self.animals:
            luck = random.randint(1, 100)
            print("Today's lucky number is", luck)
            if luck <= self.lucky_number:
                income_generated = len(animal)
                self.income_records[animal] = self.income_records.get(animal, 0) + income_generated
                self.total_income += income_generated
            else:
                print(animal, "escaped!")
        self.days_simulated += 1
        print(f"After {self.days_simulated} days, total income is {self.total_income}")

    def wait(self):
        self.generate_lucky_number()
        self.accumulate_income()

    def display_animals(self):
        if self.animals:
            print("Animals in the collection:")
            for animal in self.animals:
                print(animal)
        else:
            print("No animals.")

    def add_new_animal(self):
        animal = input("Enter the name of the new animal: ").strip().title()

        if animal == "":
            print("Invalid value.")
        elif not animal.isalpha():
            print("Invalid animal name.")
        elif animal in self.animals:
            print(f"You already have {animal}")
        else:
            cost = len(animal)
            if cost > self.total_income:
                print(f"You can't afford {animal}")
            else:
                self.animals.append(animal)
                print(f"Added {animal}.")
                self.total_income -= cost

    def get_valid_animal(self):
        while True:
            animal = input("Enter the name of the new animal: ").strip().title()
            if not animal.isalpha():
                print("Invalid animal name.")
                return

    def quit_program(self):
        self.display_summary()
        save_choice = input("Would you like to save your animals to animals.txt (Y/n)? ").strip().lower()
        if save_choice == 'y':
            self.save_animals_to_file()
            print("Animals saved to animals.txt.")
        print("Thank you for playing the Animal Accumulator :)")

    def display_summary(self):
        print(f"You finished with {len(self.animals)} animals.")
        print(f"After {self.days_simulated} days, your total income is {self.total_income}")

    def save_animals_to_file(self):
        with open("animals.txt", "w") as file:
            for animal in sorted(self.animals):
                file.write(animal + "\n")

    def display_animal_incomes(self):
        if self.income_records:
            print("Income generated by each animal:")
            for animal, income in self.income_records.items():
                print(f"{animal} earned {income}")
        else:
            print("No income records available")

    def start(self):
        self.welcome_message()
        load_choice = input("Would you like to load your animals from animals.txt (Y/n)? ")
        if load_choice.lower() == "y":
            self.load_animals_from_file()
        else:
            print("You start with these animals:")
            self.display_animals()

        while True:
            self.display_simulation_status()
            self.display_menu()
            choice = input("Choose: ").lower()

            if choice == "w":
                self.wait()
            elif choice == "d":
                self.display_animals()
            elif choice == "a":
                self.add_new_animal()
            elif choice == "q":
                self.quit_program()
                break
            else:
                print("Invalid choice.")

    def load_animals_from_file(self):
        try:
            with open("animals.txt", "r") as file:
                for line in file:
                    animal = line.strip()
                    self.animals.append(animal)
        except FileNotFoundError:
            print("No animals.txt file found. Starting with no animals.")

    def display_simulation_status(self):
        print(f"After {self.days_simulated} days, you have "
              f"{len(self.animals)} animals and your total income is "
              f"{self.total_income}")

    def display_menu(self):
        print("(W)ait\n(D)isplay animals\n(A)dd new animal\n(Q)uit")


# Instantiate the program and start the main loop
animal_accumulator = AnimalAccumulator()
animal_accumulator.start()

